defmodule EBoss.Repo.Migrations.AddWorkspaceOwnerSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      add(:owner_handle, :text)
      add(:owner_display_name, :text)
    end

    flush()

    execute("""
    UPDATE workspaces AS workspace
    SET owner_handle = users.username,
        owner_display_name = users.username
    FROM users
    WHERE workspace.owner_type = 'user'
      AND workspace.owner_id = users.id
    """)

    execute("""
    UPDATE workspaces AS workspace
    SET owner_handle = organizations.slug,
        owner_display_name = organizations.name
    FROM organizations
    WHERE workspace.owner_type = 'organization'
      AND workspace.owner_id = organizations.id
    """)

    flush()

    validate_backfill!()

    execute("""
    ALTER TABLE workspaces
    ADD CONSTRAINT workspaces_owner_handle_not_null
    CHECK (owner_handle IS NOT NULL)
    NOT VALID
    """)

    execute("""
    ALTER TABLE workspaces
    ADD CONSTRAINT workspaces_owner_display_name_not_null
    CHECK (owner_display_name IS NOT NULL)
    NOT VALID
    """)

    execute("ALTER TABLE workspaces VALIDATE CONSTRAINT workspaces_owner_handle_not_null")
    execute("ALTER TABLE workspaces VALIDATE CONSTRAINT workspaces_owner_display_name_not_null")

    alter table(:workspaces) do
      modify(:owner_handle, :text, null: false)
      modify(:owner_display_name, :text, null: false)
    end

    execute("ALTER TABLE workspaces DROP CONSTRAINT workspaces_owner_handle_not_null")
    execute("ALTER TABLE workspaces DROP CONSTRAINT workspaces_owner_display_name_not_null")
  end

  def down do
    alter table(:workspaces) do
      remove(:owner_display_name)
      remove(:owner_handle)
    end
  end

  defp validate_backfill! do
    result =
      repo().query!(
        """
        SELECT owner_type, owner_id, id
        FROM workspaces
        WHERE owner_handle IS NULL OR owner_display_name IS NULL
        ORDER BY inserted_at ASC
        LIMIT 5
        """,
        []
      )

    case result.rows do
      [] ->
        :ok

      rows ->
        sample =
          Enum.map_join(rows, ", ", fn [owner_type, owner_id, workspace_id] ->
            "#{owner_type}:#{owner_id} (workspace #{workspace_id})"
          end)

        raise """
        Could not backfill workspace owner snapshots for all rows.
        Resolve or remove orphaned workspaces before running this migration.
        Sample rows: #{sample}
        """
    end
  end
end
