defmodule EBoss.Repo.Migrations.AddArchivalSlugAndCloak do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workspaces) do
      add(:archived_at, :utc_datetime_usec)
      add(:encrypted_settings, :binary)
    end

    flush()

    migrate_to_encrypted(:workspaces, :id, :settings, :encrypted_settings)

    alter table(:workspaces) do
      remove(:settings)
    end

    drop_if_exists(
      unique_index(:workspaces, [:owner_type, :owner_id, :slug],
        name: "workspaces_unique_slug_per_owner_index"
      )
    )

    create(
      unique_index(:workspaces, [:owner_type, :owner_id, :slug],
        where: "((archived_at IS NULL))",
        name: "workspaces_unique_slug_per_owner_index"
      )
    )

    alter table(:workspace_memberships) do
      add(:archived_at, :utc_datetime_usec)
    end

    drop_if_exists(
      unique_index(:workspace_memberships, [:workspace_id, :user_id],
        name: "workspace_memberships_unique_membership_index"
      )
    )

    create(
      unique_index(:workspace_memberships, [:workspace_id, :user_id],
        where: "((archived_at IS NULL))",
        name: "workspace_memberships_unique_membership_index"
      )
    )

    alter table(:tokens) do
      add(:encrypted_extra_data, :binary)
    end

    flush()

    migrate_to_encrypted(:tokens, :jti, :extra_data, :encrypted_extra_data)

    alter table(:tokens) do
      remove(:extra_data)
    end

    alter table(:organizations) do
      add(:archived_at, :utc_datetime_usec)
      add(:encrypted_settings, :binary)
    end

    flush()

    migrate_to_encrypted(:organizations, :id, :settings, :encrypted_settings)

    alter table(:organizations) do
      remove(:settings)
    end

    drop_if_exists(unique_index(:organizations, [:slug], name: "organizations_unique_slug_index"))

    create(
      unique_index(:organizations, [:slug],
        where: "((archived_at IS NULL))",
        name: "organizations_unique_slug_index"
      )
    )

    alter table(:memberships) do
      add(:archived_at, :utc_datetime_usec)
    end

    drop_if_exists(
      unique_index(:memberships, [:user_id, :organization_id],
        name: "memberships_unique_user_organization_index"
      )
    )

    create(
      unique_index(:memberships, [:user_id, :organization_id],
        where: "((archived_at IS NULL))",
        name: "memberships_unique_user_organization_index"
      )
    )

    alter table(:invitations) do
      add(:archived_at, :utc_datetime_usec)
    end

    drop_if_exists(unique_index(:invitations, [:token], name: "invitations_unique_token_index"))

    create(
      unique_index(:invitations, [:token],
        where: "((archived_at IS NULL))",
        name: "invitations_unique_token_index"
      )
    )

    alter table(:api_keys) do
      add(:archived_at, :utc_datetime_usec)
    end

    drop_if_exists(
      unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")
    )

    create(
      unique_index(:api_keys, [:api_key_hash],
        where: "((archived_at IS NULL))",
        name: "api_keys_unique_api_key_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")
    )

    create(unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index"))

    alter table(:api_keys) do
      remove(:archived_at)
    end

    drop_if_exists(unique_index(:invitations, [:token], name: "invitations_unique_token_index"))

    create(unique_index(:invitations, [:token], name: "invitations_unique_token_index"))

    alter table(:invitations) do
      remove(:archived_at)
    end

    drop_if_exists(
      unique_index(:memberships, [:user_id, :organization_id],
        name: "memberships_unique_user_organization_index"
      )
    )

    create(
      unique_index(:memberships, [:user_id, :organization_id],
        name: "memberships_unique_user_organization_index"
      )
    )

    alter table(:memberships) do
      remove(:archived_at)
    end

    drop_if_exists(unique_index(:organizations, [:slug], name: "organizations_unique_slug_index"))

    create(unique_index(:organizations, [:slug], name: "organizations_unique_slug_index"))

    alter table(:organizations) do
      remove(:archived_at)
      add(:settings, :map, default: %{})
    end

    flush()

    migrate_from_encrypted(:organizations, :id, :encrypted_settings, :settings)

    alter table(:organizations) do
      remove(:encrypted_settings)
    end

    alter table(:tokens) do
      add(:extra_data, :map)
    end

    flush()

    migrate_from_encrypted(:tokens, :jti, :encrypted_extra_data, :extra_data)

    alter table(:tokens) do
      remove(:encrypted_extra_data)
    end

    drop_if_exists(
      unique_index(:workspace_memberships, [:workspace_id, :user_id],
        name: "workspace_memberships_unique_membership_index"
      )
    )

    create(
      unique_index(:workspace_memberships, [:workspace_id, :user_id],
        name: "workspace_memberships_unique_membership_index"
      )
    )

    alter table(:workspace_memberships) do
      remove(:archived_at)
    end

    drop_if_exists(
      unique_index(:workspaces, [:owner_type, :owner_id, :slug],
        name: "workspaces_unique_slug_per_owner_index"
      )
    )

    create(
      unique_index(:workspaces, [:owner_type, :owner_id, :slug],
        name: "workspaces_unique_slug_per_owner_index"
      )
    )

    alter table(:workspaces) do
      remove(:archived_at)
      add(:settings, :map, default: %{})
    end

    flush()

    migrate_from_encrypted(:workspaces, :id, :encrypted_settings, :settings)

    alter table(:workspaces) do
      remove(:encrypted_settings)
    end
  end

  defp migrate_to_encrypted(table, key_column, source_column, encrypted_column) do
    repo()
    |> Ecto.Adapters.SQL.query!(
      "SELECT #{key_column}, #{source_column} FROM #{table} WHERE #{source_column} IS NOT NULL",
      []
    )
    |> Map.get(:rows)
    |> Enum.each(fn [key, value] ->
      repo().query!(
        "UPDATE #{table} SET #{encrypted_column} = $1 WHERE #{key_column} = $2",
        [encrypt(value), key]
      )
    end)
  end

  defp migrate_from_encrypted(table, key_column, encrypted_column, target_column) do
    repo()
    |> Ecto.Adapters.SQL.query!(
      "SELECT #{key_column}, #{encrypted_column} FROM #{table} WHERE #{encrypted_column} IS NOT NULL",
      []
    )
    |> Map.get(:rows)
    |> Enum.each(fn [key, value] ->
      repo().query!(
        "UPDATE #{table} SET #{target_column} = $1 WHERE #{key_column} = $2",
        [decrypt(value), key]
      )
    end)
  end

  defp encrypt(value) do
    value
    |> :erlang.term_to_binary()
    |> EBoss.Vault.encrypt!()
    |> Base.encode64()
  end

  defp decrypt(value) do
    value
    |> Base.decode64!()
    |> EBoss.Vault.decrypt!()
    |> :erlang.binary_to_term()
  end
end
