defmodule EBoss.Repo.Migrations.AddEbossFolioPhase1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:folio_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "inbox"
      add :due_at, :utc_datetime_usec
      add :review_at, :utc_datetime_usec
      add :priority_position, :bigint
      add :estimated_minutes, :bigint
      add :complexity_score, :float
      add :notes, :text
      add :metadata, :map, null: false, default: %{}
      add :source, :text, null: false, default: "manual"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "folio_tasks_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :project_id, :uuid
      add :area_id, :uuid
      add :horizon_id, :uuid
      add :context_id, :uuid
    end

    create table(:folio_revision_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource_type, :text, null: false
      add :resource_id, :uuid, null: false
      add :action, :text, null: false
      add :actor_type, :text, null: false

      add :actor_id,
          references(:users,
            column: :id,
            name: "folio_revision_events_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :source, :text, null: false

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :before, :map
      add :after, :map
      add :diff, :map
      add :correlation_id, :uuid
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "folio_revision_events_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(
             :folio_revision_events,
             [:workspace_id, :resource_type, :resource_id, :occurred_at],
             name: "folio_revision_events_history_index"
           )

    create index(:folio_revision_events, [:workspace_id, :correlation_id],
             name: "folio_revision_events_correlation_index",
             where: "correlation_id IS NOT NULL"
           )

    create table(:folio_projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:folio_tasks) do
      modify :project_id,
             references(:folio_projects,
               column: :id,
               name: "folio_tasks_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:folio_projects) do
      add :title, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "active"
      add :due_at, :utc_datetime_usec
      add :review_at, :utc_datetime_usec
      add :priority_position, :bigint
      add :metadata, :map, null: false, default: %{}
      add :notes, :text
      add :source, :text, null: false, default: "manual"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "folio_projects_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :area_id, :uuid
      add :horizon_id, :uuid
      add :context_id, :uuid
    end

    create index(:folio_projects, [:workspace_id, :status],
             name: "folio_projects_workspace_status_index"
           )

    create index(:folio_projects, [:workspace_id, :due_at],
             name: "folio_projects_workspace_due_at_index"
           )

    create index(:folio_projects, [:workspace_id, :review_at],
             name: "folio_projects_workspace_review_at_index"
           )

    create table(:folio_horizons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :level, :bigint, null: false
      add :description, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "folio_horizons_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:folio_horizons, [:workspace_id, :name],
             name: "folio_horizons_unique_name_in_workspace_index"
           )

    create table(:folio_delegations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :delegated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :delegated_summary, :text, null: false
      add :quality_expectations, :text
      add :deadline_expectations_at, :utc_datetime_usec
      add :follow_up_at, :utc_datetime_usec
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "folio_delegations_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :task_id,
          references(:folio_tasks,
            column: :id,
            name: "folio_delegations_task_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :contact_id, :uuid, null: false
    end

    create unique_index(:folio_delegations, [:task_id],
             name: "folio_delegations_unique_active_task_index",
             where: "status = 'active'"
           )

    create table(:folio_contexts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "folio_contexts_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:folio_contexts, [:workspace_id, :name],
             name: "folio_contexts_unique_name_in_workspace_index"
           )

    create table(:folio_contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:folio_delegations) do
      modify :contact_id,
             references(:folio_contacts,
               column: :id,
               name: "folio_delegations_contact_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:folio_contacts) do
      add :name, :text, null: false
      add :email, :citext
      add :capability_notes, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "folio_contacts_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:folio_contacts, [:workspace_id, :email],
             name: "folio_contacts_unique_email_in_workspace_index"
           )

    create table(:folio_areas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:folio_tasks) do
      modify :area_id,
             references(:folio_areas,
               column: :id,
               name: "folio_tasks_area_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :horizon_id,
             references(:folio_horizons,
               column: :id,
               name: "folio_tasks_horizon_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :context_id,
             references(:folio_contexts,
               column: :id,
               name: "folio_tasks_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:folio_projects) do
      modify :area_id,
             references(:folio_areas,
               column: :id,
               name: "folio_projects_area_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :horizon_id,
             references(:folio_horizons,
               column: :id,
               name: "folio_projects_horizon_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :context_id,
             references(:folio_contexts,
               column: :id,
               name: "folio_projects_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:folio_areas) do
      add :name, :text, null: false
      add :description, :text
      add :review_interval_days, :bigint
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "folio_areas_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:folio_areas, [:workspace_id, :name],
             name: "folio_areas_unique_name_in_workspace_index"
           )

    create index(:folio_tasks, [:workspace_id, :status],
             name: "folio_tasks_workspace_status_index"
           )

    create index(:folio_tasks, [:workspace_id, :due_at],
             name: "folio_tasks_workspace_due_at_index"
           )

    create index(:folio_tasks, [:workspace_id, :review_at],
             name: "folio_tasks_workspace_review_at_index"
           )
  end

  def down do
    drop_if_exists index(:folio_tasks, [:workspace_id, :review_at],
                     name: "folio_tasks_workspace_review_at_index"
                   )

    drop_if_exists index(:folio_tasks, [:workspace_id, :due_at],
                     name: "folio_tasks_workspace_due_at_index"
                   )

    drop_if_exists index(:folio_tasks, [:workspace_id, :status],
                     name: "folio_tasks_workspace_status_index"
                   )

    drop_if_exists unique_index(:folio_areas, [:workspace_id, :name],
                     name: "folio_areas_unique_name_in_workspace_index"
                   )

    drop constraint(:folio_areas, "folio_areas_workspace_id_fkey")

    alter table(:folio_areas) do
      remove :workspace_id
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :review_interval_days
      remove :description
      remove :name
    end

    drop constraint(:folio_projects, "folio_projects_area_id_fkey")

    drop constraint(:folio_projects, "folio_projects_horizon_id_fkey")

    drop constraint(:folio_projects, "folio_projects_context_id_fkey")

    alter table(:folio_projects) do
      modify :context_id, :uuid
      modify :horizon_id, :uuid
      modify :area_id, :uuid
    end

    drop constraint(:folio_tasks, "folio_tasks_area_id_fkey")

    drop constraint(:folio_tasks, "folio_tasks_horizon_id_fkey")

    drop constraint(:folio_tasks, "folio_tasks_context_id_fkey")

    alter table(:folio_tasks) do
      modify :context_id, :uuid
      modify :horizon_id, :uuid
      modify :area_id, :uuid
    end

    drop table(:folio_areas)

    drop_if_exists unique_index(:folio_contacts, [:workspace_id, :email],
                     name: "folio_contacts_unique_email_in_workspace_index"
                   )

    drop constraint(:folio_contacts, "folio_contacts_workspace_id_fkey")

    alter table(:folio_contacts) do
      remove :workspace_id
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :capability_notes
      remove :email
      remove :name
    end

    drop constraint(:folio_delegations, "folio_delegations_contact_id_fkey")

    alter table(:folio_delegations) do
      modify :contact_id, :uuid
    end

    drop table(:folio_contacts)

    drop_if_exists unique_index(:folio_contexts, [:workspace_id, :name],
                     name: "folio_contexts_unique_name_in_workspace_index"
                   )

    drop constraint(:folio_contexts, "folio_contexts_workspace_id_fkey")

    drop table(:folio_contexts)

    drop constraint(:folio_delegations, "folio_delegations_workspace_id_fkey")

    drop constraint(:folio_delegations, "folio_delegations_task_id_fkey")

    drop_if_exists unique_index(:folio_delegations, [:task_id],
                     name: "folio_delegations_unique_active_task_index",
                     where: "status = 'active'"
                   )

    drop table(:folio_delegations)

    drop_if_exists unique_index(:folio_horizons, [:workspace_id, :name],
                     name: "folio_horizons_unique_name_in_workspace_index"
                   )

    drop constraint(:folio_horizons, "folio_horizons_workspace_id_fkey")

    drop table(:folio_horizons)

    drop constraint(:folio_projects, "folio_projects_workspace_id_fkey")

    drop_if_exists index(:folio_projects, [:workspace_id, :review_at],
                     name: "folio_projects_workspace_review_at_index"
                   )

    drop_if_exists index(:folio_projects, [:workspace_id, :due_at],
                     name: "folio_projects_workspace_due_at_index"
                   )

    drop_if_exists index(:folio_projects, [:workspace_id, :status],
                     name: "folio_projects_workspace_status_index"
                   )

    alter table(:folio_projects) do
      remove :context_id
      remove :horizon_id
      remove :area_id
      remove :workspace_id
      remove :updated_at
      remove :inserted_at
      remove :source
      remove :notes
      remove :metadata
      remove :priority_position
      remove :review_at
      remove :due_at
      remove :status
      remove :description
      remove :title
    end

    drop constraint(:folio_tasks, "folio_tasks_project_id_fkey")

    alter table(:folio_tasks) do
      modify :project_id, :uuid
    end

    drop table(:folio_projects)

    drop constraint(:folio_revision_events, "folio_revision_events_actor_id_fkey")

    drop constraint(:folio_revision_events, "folio_revision_events_workspace_id_fkey")

    drop_if_exists index(:folio_revision_events, [:workspace_id, :correlation_id],
                     name: "folio_revision_events_correlation_index",
                     where: "correlation_id IS NOT NULL"
                   )

    drop_if_exists index(
                     :folio_revision_events,
                     [:workspace_id, :resource_type, :resource_id, :occurred_at],
                     name: "folio_revision_events_history_index"
                   )

    drop table(:folio_revision_events)

    drop constraint(:folio_tasks, "folio_tasks_workspace_id_fkey")

    drop table(:folio_tasks)
  end
end
