defmodule EBoss.Repo.Migrations.InitAshDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :owner_type, :text, null: false
      add :owner_id, :uuid, null: false
      add :settings, :map, default: %{}
      add :metadata, :map, default: %{}
      add :visibility, :text, null: false, default: "private"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:workspaces, [:owner_type, :owner_id, :slug],
             name: "workspaces_unique_slug_per_owner_index"
           )

    create table(:workspace_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"
      add :joined_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "workspace_memberships_workspace_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id, :uuid, null: false
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:workspace_memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "workspace_memberships_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:workspace_memberships, [:workspace_id, :user_id],
             name: "workspace_memberships_unique_membership_index"
           )

    alter table(:users) do
      add :email, :citext, null: false
      add :username, :text, null: false
      add :hashed_password, :text
      add :confirmed_at, :utc_datetime_usec
      add :role, :text, null: false, default: "user"
      add :is_suspended, :boolean, null: false, default: false
      add :is_deleted, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:username], name: "users_unique_username_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :settings, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "organizations_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"
      add :joined_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "memberships_organization_id_fkey",
            type: :uuid,
            on_delete: :delete_all,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:memberships, [:user_id, :organization_id],
             name: "memberships_unique_user_organization_index"
           )

    create table(:logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :user_type, :text, null: false, default: "user"
      add :metadata, :map, null: false, default: %{}

      add :user_id,
          references(:users,
            column: :id,
            name: "logs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :target_user_id,
          references(:users,
            column: :id,
            name: "logs_target_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :org_id,
          references(:organizations,
            column: :id,
            name: "logs_org_id_fkey",
            type: :uuid,
            on_delete: :nilify_all,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :role, :text, null: false, default: "member"
      add :token, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :accepted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "invitations_organization_id_fkey",
            type: :uuid,
            on_delete: :delete_all,
            prefix: "public"
          ),
          null: false

      add :invited_by_id,
          references(:users,
            column: :id,
            name: "invitations_invited_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:invitations, [:token], name: "invitations_unique_token_index")

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")
  end

  def down do
    drop_if_exists unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop table(:api_keys)

    drop_if_exists unique_index(:invitations, [:token], name: "invitations_unique_token_index")

    drop constraint(:invitations, "invitations_organization_id_fkey")

    drop constraint(:invitations, "invitations_invited_by_id_fkey")

    drop table(:invitations)

    drop constraint(:logs, "logs_user_id_fkey")

    drop constraint(:logs, "logs_target_user_id_fkey")

    drop constraint(:logs, "logs_org_id_fkey")

    drop table(:logs)

    drop_if_exists unique_index(:memberships, [:user_id, :organization_id],
                     name: "memberships_unique_user_organization_index"
                   )

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop constraint(:memberships, "memberships_organization_id_fkey")

    drop table(:memberships)

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    drop constraint(:organizations, "organizations_owner_id_fkey")

    drop table(:organizations)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :is_deleted
      remove :is_suspended
      remove :role
      remove :confirmed_at
      remove :hashed_password
      remove :username
      remove :email
    end

    drop_if_exists unique_index(:workspace_memberships, [:workspace_id, :user_id],
                     name: "workspace_memberships_unique_membership_index"
                   )

    drop constraint(:workspace_memberships, "workspace_memberships_user_id_fkey")

    alter table(:workspace_memberships) do
      modify :user_id, :uuid
    end

    drop table(:users)

    drop constraint(:workspace_memberships, "workspace_memberships_workspace_id_fkey")

    drop table(:workspace_memberships)

    drop_if_exists unique_index(:workspaces, [:owner_type, :owner_id, :slug],
                     name: "workspaces_unique_slug_per_owner_index"
                   )

    drop table(:workspaces)
  end
end
